build fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,11 +40,30 @@ jobs:
           cmake --build . --config Release 
           cmake --install . --config Release
 
+      - name: Rename release folder
+        shell: pwsh
+        run: |
+          $releaseDir = "build/install"
+          $newDir = "QuickSoundSwitcher"
+          if (Test-Path $releaseDir) {
+              Rename-Item -Path $releaseDir -NewName $newDir
+          } else {
+              Write-Error "Release folder not found!"
+              exit 1
+          }
+
+      - name: Zip binaries folder
+        shell: pwsh
+        run: |
+          $zipFile = "build/QuickSoundSwitcher_msvc_64.zip"
+          $folder = "build/QuickSoundSwitcher"
+          Compress-Archive -Path $folder -DestinationPath $zipFile
+
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: QuickSoundSwitcher_msvc_64
-          path: build/install
+          path: build/QuickSoundSwitcher_msvc_64.zip
 
       - name: Get latest Git tag and bump version
         id: get_version
