switched back to qmake

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -23,13 +23,46 @@ jobs:
           add-tools-to-path: true
           cache: true
 
-      - name: Configure and build with CMake
+      - name: Install jom
+        id: jom-setup
+        shell: pwsh
+        run: |
+          $url = "https://download.qt.io/official_releases/jom/jom_1_1_4.zip"
+          $outputPath = "jom_1_1_4.zip"
+          Invoke-WebRequest -Uri $url -OutFile $outputPath
+          $extractPath = "jom"
+          if (-not (Test-Path $extractPath)) {
+            New-Item -ItemType Directory -Path $extractPath | Out-Null
+          }
+          Expand-Archive -Path $outputPath -DestinationPath $extractPath
+          $jomDir = "$(pwd)\jom"
+          $jomExe = "$jomDir\jom.exe"
+          if (Test-Path $jomExe) {
+            Write-Output "JOM Path: $jomDir"
+            Write-Output "::set-output name=jom_path::$jomDir"
+          } else {
+            Write-Error "jom.exe not found in $jomDir"
+            exit 1
+          }
+
+      - name: Build with qmake and jom
         shell: pwsh
         run: |
           mkdir build
           cd build
-          cmake -DCMAKE_BUILD_TYPE=Release ..
-          cmake --build . --config Release
+          qmake ..\QuickSoundSwitcher.pro CONFIG+=release
+          $jomPath = "${{ steps.jom-setup.outputs.jom_path }}"
+          & "$jomPath\jom.exe"
+          
+      - name: Remove source and object files
+        shell: pwsh
+        run: |
+          $buildDir = "build/release"
+          if (Test-Path $buildDir) {
+              Get-ChildItem -Path $buildDir -Include *.cpp, *.h, *.obj, *.res, *.qm -Recurse | Remove-Item -Force
+          } else {
+              Write-Host "Directory not found: $buildDir"
+          }
 
       - name: Deploy Qt
         shell: pwsh
